# 베이스 이미지
FROM node:16-alpine

ENV DOCKERIZE_VERSION v0.7.0
RUN apk update && \
    apk add --no-cache wget openssl && \
    wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin && \
    apk del wget

# 앱 디렉토리 생성
WORKDIR /app

# package*.json 복사 및 설치
COPY ../../package*.json ./
RUN apk update && \
    apk add --no-cache build-base python3 && \
    npm install

# 소스코드 복사
COPY . .

# 노출 포트
EXPOSE 3000

# 30초 기다리다가 그 이후에도 DB 준비 안 되면 code 1 뱉으면서 종료됨
CMD dockerize -wait tcp://db:3306 -timeout 30s && npm run start:msg:dev