# 베이스 이미지
FROM node:16-alpine

# 앱 디렉토리 생성
WORKDIR /app

# package*.json 복사 및 설치
COPY ../../package*.json ./
RUN apk update && \
    apk add --no-cache build-base python3 && \
    npm install

# 소스코드 복사
COPY . .

# 노출 포트
EXPOSE 3000