version: '3.8'

services:
  db:
    container_name: msg_db_container
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - '3306:3306'
    networks:
      - msg_network
    volumes:
      - db_data:/var/lib/mysql

  msg:
    container_name: msg_container
    build:
      context: .
      dockerfile: ./apps/msg/dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - msg_network
    depends_on:
      - db
    volumes:
      - msg_data:/app/
    command: npm run start:msg:dev

volumes:
  db_data:
  msg_data:


networks:
  msg_network:
